# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appPhoRent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Kingfisher'
  pod 'Firebase/Functions'
  pod 'RangeSeekSlider'
  # Pods for appPhoRent

end
